#!/usr/bin/env bash
# lib/cron.sh - Cron job management library for VaultWarden

set -euo pipefail

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

source "$ROOT_DIR/lib/logging.sh"
source "$ROOT_DIR/lib/system.sh"
source "$ROOT_DIR/lib/config.sh"

# Setup automated maintenance cron jobs
setup_cron_jobs() {
    local auto_mode="${1:-false}"
    _log_section "Cron Job Configuration"

    local project_root="$ROOT_DIR"
    local cron_file="/tmp/${PROJECT_NAME}-cron"

    cat > "$cron_file" <<EOF
# ${PROJECT_NAME} - Automated Maintenance Schedule
# Generated by init-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Database maintenance
0 2 * * 1 root cd $project_root && ./tools/sqlite-maintenance.sh -t full 2>&1 | logger -t sqlite-maintenance
0 6 * * * root cd $project_root && ./tools/sqlite-maintenance.sh -t quick 2>&1 | logger -t sqlite-maintenance

# System monitoring (every 5 minutes)
*/5 * * * * root cd $project_root && ./tools/monitor.sh 2>&1 | logger -t monitor

# Backup jobs (daily at 1 AM, weekly full backup on Sunday)
0 1 * * * root cd $project_root && ./tools/db-backup.sh 2>&1 | logger -t backup
0 0 * * 0 root cd $project_root && ./tools/create-full-backup.sh 2>&1 | logger -t full-backup

# Cloudflare IP updates (daily at 3 AM)
0 3 * * * root cd $project_root && ./tools/update-cloudflare-ips.sh --quiet 2>&1 | logger -t cloudflare-ips

# Log rotation and cleanup (daily at 4 AM)
0 4 * * * root find ${PROJECT_STATE_DIR}/logs -name "*.log" -size +50M -exec truncate -s 10M {} \; 2>&1 | logger -t log-cleanup
0 4 * * * root find ${PROJECT_STATE_DIR}/backups -type d -name "20*" -mtime +30 -exec rm -rf {} \; 2>&1 | logger -t backup-cleanup

EOF

    if [[ "$auto_mode" != "true" ]]; then
        _log_confirm "Install automated maintenance cron jobs?" "Y"
        read -r response
        response=${response:-Y}

        if [[ ! "$response" =~ ^[yY][eE][sS]?$ ]]; then
            _log_info "Cron job installation skipped"
            rm -f "$cron_file"
            return 0
        fi
    fi

    if crontab -l > /dev/null 2>&1; then
        local backup_cron="/tmp/crontab-backup-$(date +%Y%m%d_%H%M%S)"
        crontab -l > "$backup_cron"
        _log_info "Existing crontab backed up to: $backup_cron"

        crontab -l | grep -v "# ${PROJECT_NAME} -" | grep -v "${project_root}" | crontab -
        (crontab -l; echo; cat "$cron_file") | crontab -
    else
        crontab "$cron_file"
    fi

    rm -f "$cron_file"
    _log_success "Cron jobs installed successfully"

    if [[ "$auto_mode" != "true" ]]; then
        _log_info "Installed cron schedule:"
        echo "  Database maintenance: Weekly full (Mon 2AM), Daily quick (6AM)"
        echo "  System monitoring: Every 5 minutes"
        echo "  Backups: Daily database (1AM), Weekly full (Sun 12AM)"
        echo "  Cloudflare IPs: Daily update (3AM)"
        echo "  Cleanup: Daily log rotation and old backup removal (4AM)"
    fi

    _enable_service "cron" || _enable_service "crond" || {
        _log_warning "Could not enable cron service automatically"
        _log_info "Ensure cron service is running: systemctl enable --now cron"
    }

    return 0
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    _log_debug "lib/cron.sh loaded successfully"
else
    _log_warning "lib/cron.sh should be sourced, not executed directly."
fi