daemon=300
syslog=yes
mail=root
mail-failure=root
pid=/var/run/ddclient.pid

protocol=cloudflare
use=web, web=checkip.amazonaws.com
ssl=yes
login=token
password=${CF_API_TOKEN}
zone=${DDCLIENT_DOMAIN}
host=${DDCLIENT_HOST}
